# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-19 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptmessage',
            options={'ordering': ['created']},
        ),
        migrations.RenameField(
            model_name='cryptmessage',
            old_name='created_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='cryptmessage',
            old_name='crypted_text',
            new_name='text_crypted',
        ),
    ]
