# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-20 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypt', '0005_post_crypted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='crypted_type',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
